version: "3.3"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3
    environment:
      - discovery.type=single-node
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=changeme
      - xpack.security.enabled=true
    ports:
      - 9200:9200
      - 9300:9300
    healthcheck:
      test: [ "CMD", "curl", "-s", "-u", "elastic:changeme", "--fail" , "http://localhost:9200/_cluster/health?wait_for_status=green" ]
